Adding updates for SDS jenkins config
hmcts/hmcts.github.io pull request #101
Opened 2021-08-18 13:23 UTC by endakelly

2021-08-18 13:25 UTC, timja reviewed
can you please attach a full page screenshot?

2021-08-18 14:51 UTC, endakelly commented
![image](https://user-images.githubusercontent.com/80516065/129920496-70e4f498-a391-4a20-8648-42ffbfb7c75d.png)

2021-08-24 09:49 UTC, timja requested changes

2021-08-24 09:49 UTC, timja commented on source/onboarding/team/index.html.md.erb
> +There are Jenkins servers setup for each business area within Platform Operations: CFT and SDS
Platform Operations is not a business area

```suggestion
There are Jenkins servers for: CFT (Civil, Family & Tribunals) and SDS (Shared Digital Services)
```

2021-08-24 09:49 UTC, timja commented on source/onboarding/team/index.html.md.erb
> +SDS stands for Shared Services
```suggestion
```

2021-08-24 09:49 UTC, timja commented on source/onboarding/team/index.html.md.erb
> +        CFT: [cnp-jenkins-config](https://github.com/hmcts/cnp-jenkins-config/pull/402)
this screenshot you provided shows that this is not rendering properly

2021-08-24 10:48 UTC, endakelly commented
![image](https://user-images.githubusercontent.com/80516065/130603904-9db0e3f2-ad1c-4106-bd28-baa2754ad125.png)

2021-08-24 11:04 UTC, msl8r approved these changes
LGTM (I think) :D

2021-08-24 12:40 UTC, timja approved these changes
let's see how it goes

2021-08-24 14:32 UTC, merged